# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types:
  - pre-commit
  - pre-push
  - commit-msg
repos:
  - repo: https://github.com/hadolint/hadolint/
    rev: v2.13.0-beta
    hooks:
      - id: hadolint-docker
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args:
          - -d
          - relaxed
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.27.0
    hooks:
      - id: commitizen
  - repo: local
    hooks:
      - id: fmt
        name: "Format go files"
        entry: make
        args: ["fmt"]
        language: system
        types: [go]
        pass_filenames: false
      - id: lint
        name: "Lint go files"
        entry: make
        args: ["lint"]
        language: system
        types: [go]
        pass_filenames: false
      - id: test
        name: "Unit testing"
        entry: make
        args: ["test-unit"]
        language: system
        types: [go]
        pass_filenames: false
        stages: [pre-push]
      - id: go-licenses
        name: "Go Licensing"
        entry: make
        args: ["check-licenses"]
        language: system
        types: [go]
        pass_filenames: false
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
    - id: shellcheck
      args: ["--severity=warning"]  # only show errors and warnings
exclude: "^.*/THIRD_PARTY_NOTICES/.*"

