# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

substitutions:
  _IMAGE_REGISTRY: "us-docker.pkg.dev/${PROJECT_ID}/catalog"

options:
  logging: CLOUD_LOGGING_ONLY
  # Enforce Cloud Build to generate provenance.
  requestedVerifyOption: VERIFIED
  dynamic_substitutions: true

steps:
  - id: build
    name: gcr.io/cloud-builders/docker
    dir: images
    env:
      - "REGISTRY=${_IMAGE_REGISTRY}"
    script: |
      #!/usr/bin/env bash

      make build

  - id: test
    name: gcr.io/cloud-builders/docker
    dir: images
    waitFor:
      - build
    env:
      - "REGISTRY=${_IMAGE_REGISTRY}"
    script: |
      #!/usr/bin/env bash

      curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64 && \
        chmod +x container-structure-test-linux-amd64 && \
        mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test

      make test

  - id: scan
    name: us-docker.pkg.dev/scaevola-builder-integration/release/scanvola/scanvola:latest
    waitFor:
      - build
    args:
      - "--on_demand"
      # Base Images
      - "--image=${_IMAGE_REGISTRY}/gcb-base:ubuntu22"
      # Tool Images
      - "--image=${_IMAGE_REGISTRY}/docker/dind:debian12"
      - "--image=${_IMAGE_REGISTRY}/docker/cli:debian12"
      - "--image=${_IMAGE_REGISTRY}/gar-upload:ubuntu22"
      - "--image=${_IMAGE_REGISTRY}/gcloud:ubuntu22"
      - "--image=${_IMAGE_REGISTRY}/git:ubuntu22"
      - "--image=${_IMAGE_REGISTRY}/syft:ubuntu22"
      - "--image=${_IMAGE_REGISTRY}/app-engine:ubuntu22"
      - "--image=${_IMAGE_REGISTRY}/cloud-deploy:ubuntu22"
      - "--image=${_IMAGE_REGISTRY}/cloud-storage:ubuntu22"
      - "--image=${_IMAGE_REGISTRY}/cloud-run:ubuntu22"
      - "--image=${_IMAGE_REGISTRY}/cloud-function:ubuntu22"
      - "--image=${_IMAGE_REGISTRY}/gke-deploy:ubuntu22"
      - "--image=${_IMAGE_REGISTRY}/builder:debian12"
      - "--image=${_IMAGE_REGISTRY}/go:ubuntu22"
      - "--image=${_IMAGE_REGISTRY}/nodejs-steps:ubuntu22"
      - "--image=${_IMAGE_REGISTRY}/python-steps:ubuntu22"
      - "--image=${_IMAGE_REGISTRY}/maven-steps:ubuntu22"

# Push the images.
images:
  - ${_IMAGE_REGISTRY}/gcb-base:latest
  - ${_IMAGE_REGISTRY}/gcb-base:ubuntu22
  - ${_IMAGE_REGISTRY}/docker/dind:latest
  - ${_IMAGE_REGISTRY}/docker/dind:debian12
  - ${_IMAGE_REGISTRY}/docker/cli:latest
  - ${_IMAGE_REGISTRY}/docker/cli:debian12
  - ${_IMAGE_REGISTRY}/gar-upload:latest
  - ${_IMAGE_REGISTRY}/gar-upload:ubuntu22
  - ${_IMAGE_REGISTRY}/gcloud:latest
  - ${_IMAGE_REGISTRY}/gcloud:ubuntu22
  - ${_IMAGE_REGISTRY}/git:latest
  - ${_IMAGE_REGISTRY}/git:ubuntu22
  - ${_IMAGE_REGISTRY}/syft:latest
  - ${_IMAGE_REGISTRY}/syft:ubuntu22
  - ${_IMAGE_REGISTRY}/app-engine:latest
  - ${_IMAGE_REGISTRY}/app-engine:ubuntu22
  - ${_IMAGE_REGISTRY}/cloud-deploy:latest
  - ${_IMAGE_REGISTRY}/cloud-deploy:ubuntu22
  - ${_IMAGE_REGISTRY}/cloud-storage:latest
  - ${_IMAGE_REGISTRY}/cloud-storage:ubuntu22
  - ${_IMAGE_REGISTRY}/cloud-run:latest
  - ${_IMAGE_REGISTRY}/cloud-run:ubuntu22
  - ${_IMAGE_REGISTRY}/cloud-function:latest
  - ${_IMAGE_REGISTRY}/cloud-function:ubuntu22
  - ${_IMAGE_REGISTRY}/gke-deploy:latest
  - ${_IMAGE_REGISTRY}/gke-deploy:ubuntu22
  - ${_IMAGE_REGISTRY}/builder:latest
  - ${_IMAGE_REGISTRY}/builder:debian12
  - ${_IMAGE_REGISTRY}/go:latest
  - ${_IMAGE_REGISTRY}/go:ubuntu22
  - ${_IMAGE_REGISTRY}/nodejs-steps:latest
  - ${_IMAGE_REGISTRY}/nodejs-steps:ubuntu22
  - ${_IMAGE_REGISTRY}/python-steps:latest
  - ${_IMAGE_REGISTRY}/python-steps:ubuntu22
  - ${_IMAGE_REGISTRY}/maven-steps:latest
  - ${_IMAGE_REGISTRY}/maven-steps:ubuntu22
