# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Container structure test to validate the go image.
schemaVersion: "2.0.0"

commandTests:
  - name: go1.20 installed
    envVars:
      - key: GOOGLE_GO_VERSION
        value: "1.20"
    command: "entrypoint.sh"
    args: ["go", "version"]
    expectedOutput:
      - "go version go1.20"

  - name: go1.21 installed
    envVars:
      - key: GOOGLE_GO_VERSION
        value: "1.21"
    command: "entrypoint.sh"
    args: ["go", "version"]
    expectedOutput:
      - "go version go1.21"

  - name: go1.19 not installed
    envVars:
      - key: GOOGLE_GO_VERSION
        value: "1.19"
    command: "entrypoint.sh"
    args: ["go", "version"]
    expectedError:
      - "go version 1.19 not installed"
    exitCode: 1

  - name: go-wrapper installed
    command: "go-wrapper"
    args: ["--help"]
    exitCode: 0

metadataTest:
  envVars:
    - key: GOOGLE_GO_VERSION
      value: 1.21
  user: nonroot
  entrypoint: ["entrypoint.sh"]
  cmd: ["go"]
