# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Container structure test to validate the python image.
schemaVersion: "2.0.0"

commandTests:
  - name: python 3.8 installed
    envVars:
      - key: GOOGLE_PYTHON_VERSION
        value: "3.8"
    command: "entrypoint.sh"
    args: ["python3", "--version"]
    expectedOutput:
      - "Python 3.8.18"
  - name: pip 23.3.2 installed (for python 3.8)
    envVars:
      - key: GOOGLE_PYTHON_VERSION
        value: "3.8"
    command: "entrypoint.sh"
    args: ["pip", "--version"]
    expectedOutput:
      - "pip 23.3.2"
  - name: wheel 0.42.0 installed (for python 3.8)
    envVars:
      - key: GOOGLE_PYTHON_VERSION
        value: "3.8"
    command: "entrypoint.sh"
    args: ["python3", "-m", "wheel", "version"]
    expectedOutput:
      - "wheel 0.42.0"

  - name: python 3.10 installed
    envVars:
      - key: GOOGLE_PYTHON_VERSION
        value: "3.10"
    command: "entrypoint.sh"
    args: ["python3", "--version"]
    expectedOutput:
      - "Python 3.10.12"
  - name: pip 22.0.2 installed (for python 3.10)
    envVars:
      - key: GOOGLE_PYTHON_VERSION
        value: "3.10"
    command: "entrypoint.sh"
    args: ["pip", "--version"]
    expectedOutput:
      - "pip 22.0.2"
  - name: wheel 0.37.1 installed (for python 3.10)
    envVars:
      - key: GOOGLE_PYTHON_VERSION
        value: "3.10"
    command: "entrypoint.sh"
    args: ["python3", "-m", "wheel", "version"]
    expectedOutput:
      - "wheel 0.37.1"

  - name: python 3.12 installed
    envVars:
      - key: GOOGLE_PYTHON_VERSION
        value: "3.12"
    command: "entrypoint.sh"
    args: ["python3", "--version"]
    expectedOutput:
      - "Python 3.12.0"
  - name: pip3 23.2.1 installed (for python 3.12)
    envVars:
      - key: GOOGLE_PYTHON_VERSION
        value: "3.12"
    command: "entrypoint.sh"
    args: ["pip3", "--version"]
    expectedOutput:
      - "pip 23.2.1"
  - name: wheel 0.41.2 installed (for python 3.12)
    envVars:
      - key: GOOGLE_PYTHON_VERSION
        value: "3.12"
    command: "entrypoint.sh"
    args: ["python3", "-m", "wheel", "version"]
    expectedOutput:
      - "wheel 0.41.2"
  - name: system python installed
    command: "python3"
    args: ["--version"]
    expectedOutput:
      - "Python 3.10.12"
  - name: python 3.7 not installed
    envVars:
      - key: GOOGLE_PYTHON_VERSION
        value: "3.7"
    command: "entrypoint.sh"
    args: ["python", "--version"]
    expectedError:
      - "python version 3.7 not installed"
    exitCode: 1

  - name: "python-steps is installed"
    command: "python-steps"
    args: ["--help"]
    exitCode: 0

metadataTest:
  envVars:
    - key: GOOGLE_PYTHON_VERSION
      value: 3.12
  user: nonroot
  entrypoint: ["entrypoint.sh"]
  cmd: ["python3"]
