# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Container structure test to validate the nodejs image.
schemaVersion: "2.0.0"

commandTests:
  - name: node 18 installed
    envVars:
      - key: GOOGLE_NODEJS_VERSION
        value: "18"
    command: "entrypoint.sh"
    args: ["node", "--version"]
    expectedOutput:
      - "v18.19.0"

  - name: node 20 (default) installed
    command: "node"
    args: ["--version"]
    expectedOutput:
      - "v20.10.0"

  - name: node 19 not installed
    envVars:
      - key: GOOGLE_NODEJS_VERSION
        value: "19"
    command: "entrypoint.sh"
    args: ["node", "--version"]
    expectedError:
      - "nodejs version 19 not installed"
    exitCode: 1

  - name: "node-steps is installed"
    command: "node-steps"
    args: ["--help"]
    exitCode: 0

metadataTest:
  envVars:
    - key: GOOGLE_NODEJS_VERSION
      value: 20
  user: nonroot
  entrypoint: ["entrypoint.sh"]
  cmd: ["node"]
